### PR TITLE
removed _name member from Material_d class

### PR DESCRIPTION
**Pull request by moes1**

### CODE REVIEW

**Comment by obrien20** [comment]
It is nice to have a material name. I can imagine std::string causes grief on GPUs, maybe make it char *

**Comment by moes1** [comment]
As this is written, every Material_d class object that lives on the GPU is created from a corresponding Material object that lives on the CPU. If you need the name you can get it from the corresponding Material object that lives on the host. You can even access it on the GPU by doing a zero-copy access over PCIe. Is there a reason one would need the name to also reside on the GPU?

**Comment by obrien20** [comment]
ok, that sounds reasonable.

**Comment by bleile1** [comment]
This looks fine to me

**Pull request merged**
